### ISSUE TITLE
comment translation strings

### ISSUE THREAD

**Issue by konradsroka** [Themekraft/_tk#10]
Hier noch einmal aufgelistet:
1. "Leave a Reply"
2. "Leave a Reply to %s"
3. "Cancel Reply"
4. "Post Comment"
5. "You may use these <abbr title=\"HyperText Markup Language\">HTML</abbr> tags and attributes:"

**Comment by svenl77** [comment]
@konradsroka is this fixed? Please reopen and create a pull request if possible ;-)
