### ISSUE TITLE
Formatting of Next and Previous Posts Links

### ISSUE THREAD

**Issue by dylan-k** [Themekraft/_tk#11]
I presume that the single post pages' "next" and "previous" links are supposed to float right and left, respectively, but in my version of _tk (v. 0.1) they do not. I have found a fix, however (I don't yet know how to do a pull request so I'll post it here). It involves the addition of bootstrap's "pull" classes, and some CSS to clear the floats.

on file template-tags.php change lines 43-49 to read as follows:

```php
		<?php if ( get_next_posts_link() ) : ?>
		<div class="nav-previous pull-left"><?php next_posts_link( __( '<span class="meta-nav">&larr;</span> Older posts', '_tk' ) ); ?></div>
		<?php endif; ?>

		<?php if ( get_previous_posts_link() ) : ?>
		<div class="nav-next pull-right"><?php previous_posts_link( __( 'Newer posts <span class="meta-nav">&rarr;</span>', '_tk' ) ); ?></div>
		<?php endif; ?>
```

and then add some css:
```css
div#comments {clear:both; padding-top:2em;}
```

**Comment by svenl77** [comment]
Has this patch ever find its path into the theme? @dylan-k long time ago... Anyway are you willing to create a pull request ?

**Comment by dylan-k** [comment]
I can do that within a few days.

**Comment by svenl77** [comment]
@konradsroka can we close this ticket? Is it outdated or still an issue?

**Comment by dylan-k** [comment]
Looks good to me. This may also affect the pagers that appear when posts are broken into parts, but let's close this one.
