### ISSUE TITLE
Question: How to create full width page?

### ISSUE THREAD

**Issue by juricazuanovic** [Themekraft/_tk#16]
I'm having problem creating full width page template, since there's 
`<div id="content" class="main-content-inner col-sm-12 col-md-8">` in the header.php
Can you help me?

**Comment by mmcshinsky** [comment]
This is example code I used in the header.php to conditionally change the width:
`<div id="content" class="main-content-inner col-sm-12 <?php if(is_page_template('page.php')) {?>col-md-8<?php } else { ?>col-md-12<?php }?>">`
