### ISSUE TITLE
Menu Dropdown not working

### ISSUE THREAD

**Issue by tamimibrahim** [Themekraft/_tk#17]
I did set up everything properly, but not sure why themes dropdown not working. I didn't get any error in console. Tested browser was Google Chrome 31.0.1650.63 Ubuntu 12.04 (31.0.1650.63-0ubuntu0.12.04.1~20131204.1)

**Comment by alexbohariuc** [comment]
Hey guys.
I found the fix:

Look for line 59. You should see this: 
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">

Then, replace .navbar-responsive-collapse with .navbar-collapse.
It should work as expected.

**Comment by tamassy** [comment]
Hi, I've just installed the theme and assigned the right menu to the navigation. but when it shrinks the toggle button doesn't open.
@alexbohariuc  i can't see the first bit of the code i should look for.

Anyway, this is an error i found when i tried to implement WP/Bootstrap other times. i think it could be some little setting to change.

A

**Comment by tamassy** [comment]
@alexbohariuc i've seen your edit on the code, you meant the header.php

thanks for this. can't wait to test it!

A

**Comment by tamassy** [comment]
I've tested the updated header.php and it works perfectly.
it was just pointing the wrong class than.

Great job @alexbohariuc

**Comment by svenl77** [comment]
pull request merged great job!

**Comment by webguy262** [comment]
I'm using the latest _tk and mhy menu dropdown is not working. The ".navbar-responsive-collapse | .navbar-collapse" is not the issue as I have the right class.

Here's the site: http://devopsinst.staging.wpengine.com/
