### ISSUE TITLE
review team feedback 

### ISSUE THREAD

**Issue by svenl77** [Themekraft/_tk#45]
https://themes.trac.wordpress.org/ticket/23280#comment:3

**Comment by tamassy** [comment]
let me know if you need a help.

**Comment by svenl77** [comment]
@tamassy If you able to help, you are more than welcome. I'm not finding the time at the moment.

**Comment by tamassy** [comment]
Yep, going to give a help soon as i will use this template for a project, so i'll let you know.
Thank you and really good job.
A

**Comment by svenl77** [comment]
Hi @tamassy,

Did you find the time to investigate in the issues?

Per https://make.wordpress.org/themes/handbook/review/required/
Declare licenses of any resources included in your reatme.txt file (which you might like to change to readme.txt instead).
wp_bootstrap_navwalker license GPL2
Glyphicons license MIT
Escape user data - http://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data#Escaping:_Securing_Output
e.g. in custom-header.php you have function _tk_admin_header_image(), see how escaping user data has been implemented in Twenty Thirteen theme twentythirteen_admin_header_image(). And you might want to compare the rest of that new sanitized custom-header.php file with you own. Having said that, you might also want to consider latest from _s https://github.com/fklein-lu/_s/commit/0b7df4a5293435249efbd99486355155a63fdeca
Link in your theme's description must be either the Author URL/Theme URL. Have to get this #3 one confirmed by a TRT Admin as it was the rule before and it might have changed now :)

Find the latest comments here: https://themes.trac.wordpress.org/ticket/23280#comment:4

Please let me know, otherwise I need to dig into it.

Thanks,
Sven

**Comment by tamassy** [comment]
Hi Sven, unluckily not yet. hope to have time soon!
