### ISSUE TITLE
Would be nice to add Woocommerce support?

### ISSUE THREAD

**Issue by pulpomarketing** [Themekraft/_tk#53]

**Comment by richlloydmiles** [comment]
I am working on a WooCommerce Branch - https://github.com/richlloydmiles/_rm Will update when ready to be used in a production environment.

**Comment by svenl77** [comment]
Hi @richlloydmiles I will close this issue. If you have a pull request for the WC support let me know.

**Comment by richlloydmiles** [comment]
Opened a pull request for this.

**Comment by svenl77** [comment]
thanks ;)
