### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by aspexi** [Themekraft/_tk#61]
Hi Guys,

I may be blind but some time ago there was instruction how to customize theme name.

Something like "Search for:  _tk and replace with:  Megatherium" etc.

I cannot find it in _tk doc on GitHub.

Is it bug or feature?

Thanks
Krzysztof

**Comment by ginsterbusch** [comment]
One wonders what you are talking about.

But normally it would go like this:
You open up all files, and do a search and replace over all documents, search keyword "_tk", replace with "my_themename"; thus effectively (and properly) namespacing your theme.

cu, w0lf.

**Comment by aspexi** [comment]
Hi w0lf,

I have found it:

Search for: '_tk' and replace with: 'megatherium'
Search for: _tk_ and replace with: megatherium_
Search for:  _tk (first sign is space here) and replace with:  Megatherium (first sign is space here)
Search for: _tk- and replace with: megatherium-

This was on some page related to _tk - cannot remember if on GitHub or official website but it's gone now (or I cannot find it).

Reference: https://wiki.thingsandstuff.org/WP_themes

Krzysztof
