### ISSUE TITLE
Theme Check Information

### ISSUE THREAD

**Issue by mr910** [Themekraft/_tk#62]
One or more errors were found for _tk.

REQUIRED:.sticky css class is needed in your theme css.
REQUIRED:.gallery-caption css class is needed in your theme css.
REQUIRED:.bypostauthor css class is needed in your theme css.
WARNING: Your theme appears to be in the wrong directory for the theme name. The directory name must match the slug of the theme. This theme's correct slug and text-domain is _tk.
WARNING: Found wrong tag, remove nightshift from your style.css header.
WARNING: Found wrong tag, remove coffee from your style.css header.
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'You may use these HTML tags and attributes:'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Post Comment'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Leave a Reply'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Leave a Reply to %s'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments 'Cancel Reply'
WARNING: .project Hidden Files or Folders found.
RECOMMENDED: Screenshot size should be 880x660, to account for HiDPI displays. Any 4:3 image size is acceptable, but 1200x900 is preferred.
RECOMMENDED: No reference to the_post_thumbnail() was found in the theme. It is recommended that the theme implement this functionality instead of using custom fields for thumbnails.
RECOMMENDED: No reference to add_theme_support( "title-tag" ) was found in the theme. It is recommended that the theme implement this functionality for WordPress 4.1 and above.
INFO: Possible hard-coded links were found in the file footer.php.
Line 24: <?php printf( __( 'Theme: %1$s by %2$s.', '_tk' ), '_tk', '<a href='http://underscores.me/' rel='designer'>Underscores.me</a>' ); ?>
INFO: Only one text-domain is being used in this theme. Make sure it matches the theme's slug correctly so that the theme will be compatible with WordPress.org language packs.
The domain found is _tk

**Comment by svenl77** [comment]
I have just released a new version with no issues from theme check
