### ISSUE TITLE
Customize bootstrap

### ISSUE THREAD

**Issue by JMRegan** [Themekraft/_tk#67]
This is just a question and not an issue.

I want to customize bootstrap for use in a _tk child theme.  Is it as simple as copying bootstrap files over the existing files I have already downloaded in _tk-master? Or have changes been made that would affect the theme?

**Comment by ginsterbusch** [comment]
AFAIK the only changes for (better working together with) WordPress are stored in separate files. The updates to Bootstrap in the repository are normally done in a similar manner as the one suggested by yours truly; ie. by downloading and replacing the resources (thus overwriting them).

Addition: Last commit says: "Copied Bootstrap 3.3.6 files over the old ones." - so, yeah, just go for it. Bootstrap is stored in a separate directory anyway.

cu, w0lf.

**Comment by JMRegan** [comment]
Thanks. That's cleared that one up then.
