### ISSUE TITLE
no child now child

### ISSUE THREAD

**Issue by maryannewelch** [Themekraft/_tk#86]
I went to update a site I built in _tk to wp 4.6 the other day and saw _tk had an "update " available.  

When I set that site up I foolishly bought your idea that I didn't need a child theme (now slapping myself awake). So no there is no way I can go from _tk version "0" to any other number without blowing the entire site away. 

So here's my question: Do you have a _tk child theme that calls all the css files - in arrays perhaps?

**Comment by svenl77** [comment]
Hi @maryannewelch, sorry for your trouble. _tk is a starter theme. You can just rename it and start your own or use it as parent and create a child.

just create a style.css and add this on top:

/*Theme Name: _tk-child
Theme URI: http://themekraft.com/
Description: Just an example
Author: your name
Author URI: link to yourt site 
Template: _tk
Version: 1.0
*/

Please see here: https://codex.wordpress.org/Child_Themes
